apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydeployment
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: ghcr.io/akash3069/myweb:79f041c
        name: nginx
        ports:
        - containerPort: 80

