apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydeployment
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ghcr.io/akash3069/myweb:79f041c
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret

